export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

plugins=(git
zoxide
starship
zsh-autosuggestions 
zsh-syntax-highlighting
sudo)

source $ZSH/oh-my-zsh.sh

alias ls="eza --icons"
alias cd="z"
alias v="nvim"
alias x="clear"
alias lt="eza --tree --icons"
alias rm="rm -rf"
alias :q="exit"
alias ba="bash"
alias rn="ranger"
alias gi="git add * && git commit -m "silly-configs""
alias la="lazygit"
alias gh="flatpak run io.github.shiftey.Desktop"
. /home/jadu/.nix-profile/etc/profile.d/nix.sh
if [ -e /home/jadu/.nix-profile/etc/profile.d/nix.sh ]; then . /home/jadu/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer

# Enable colors in zsh
autoload -U colors && colors

# Custom prompt with colors
#PROMPT='%F{blue}%~%f
#%F{blue}λ %f'
